name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: nawaraing/github-profile-3d-contrib@0.7.2
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          USERNAME: nawaraing
      - name: Commit & Push
        run: |
          git config user.name nawaraing
          git config user.email nawaddaing@gmail.com
          git add -A .
          git commit -m "generated"
          git push
